title = "Computer Systems: A Programmer's Perspective, 3rd edition"
language = "en"
author = [
    "Randal E. Bryant",
    "David R. O'Hallaron"
]
publisher = "Pearson Education"
isbn = "978-0-13-409266-9"
